language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan jwt:secret
  - php artisan clear-compiled && php artisan optimize:clear
  - php artisan config:cache

script:
  - vendor/bin/phpunit

notifications:
email:
  on_success: never
  on_failure: always
